# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mia', '0004_auto_20170528_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default=1234, max_length=20),
            preserve_default=False,
        ),
    ]
