# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mia', '0005_post_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='boardId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mia.Board'),
            preserve_default=False,
        ),
    ]
