# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 05:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mia', '0006_auto_20170529_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='korName',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
