# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 07:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mia', '0007_board_korname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=30)),
                ('korName', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='board',
            name='categoryId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mia.Category'),
            preserve_default=False,
        ),
    ]
